# This is a basic workflow to help you get started with Actions

name: frontendCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ] 
    paths:
      - 'frontend/**'

#Running your workflow only

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/setup-gcloud@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_CREDENTIALS}}'
      
      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build . -t openauxfrontend
      
      - name: Tag Image
        run: |
          docker tag openauxfrontend gcr.io/openaux/openauxfrontend
      
      - name: Push Image
        run: |
          docker push gcr.io/openaux/openauxfrontend 
          
      - name: Deploy
        run: |
          gcloud run deploy openauxfrontend:latest \
          --region us-central1-a \
          --image gcr.io/openaux/openauxfrontend \
          --platform managed \
          --allow-unauthenticated \
          --project openaux \
          --update-env-vars REACT_APP_BACKEND=${{secrets.REACT_APP_BACKEND}},REACT_APP_ICECAST=${{secrets.REACT_APP_ICECAST}}
        
        
        
