# This is a basic workflow to help you get started with Actions

name: frontendCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ] 
    paths:
      - 'frontend/**'

#Running your workflow only

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/openauxfrontend:latest
          
      - name: Deploy
        run: |
          gcloud run deploy openauxfrontend:latest \
          --region us-central1-a \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/openauxfrontend \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          ----update-env-vars backend=${{secrets.backendurl}}
        
        
        
